name = "free-qr-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[vars]
SMTP_FROM = "noreply@free-qrcode.app"

[[r2_buckets]]
binding = "QR_IMAGES"
bucket_name = "qr-saas-images"

[[d1_databases]]
binding = "DB"
database_name = "free-qr-api-db"
database_id = "1bdd4b44-714d-4af1-931d-cb5b253ffc76"
migrations_dir = "migrations"