name = "free-qr-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "EMAIL_WORKER"
service = "emailworker"

[vars]
API_BASE_URL = "https://free-qr-api.messiasayi.workers.dev"
CORS_ORIGINS = "https://free-qr-code-saas.getcongo.com"
FRONTEND_URL = "https://free-qr-code-saas.getcongo.com"
SMTP_FROM = "noreply@free-qrcode.app"

[[r2_buckets]]
binding = "QR_IMAGES"
bucket_name = "qr-saas-images"

[[d1_databases]]
binding = "DB"
database_name = "free-qr-api-db"
database_id = "1bdd4b44-714d-4af1-931d-cb5b253ffc76"
migrations_dir = "migrations"